# Maven build and test pipeline for Azure DevOps with browser setup for automation

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Checkout the repository
- task: Checkout@1

# Step 2: Install Microsoft Edge, Edge WebDriver, Google Chrome, and ChromeDriver
- script: |
    sudo apt-get update
    # Install Microsoft Edge and Edge WebDriver
    sudo apt-get install -y microsoft-edge-stable
    sudo apt-get install -y selenium-edge-driver
    which msedgedriver
    
    # Install Google Chrome and ChromeDriver
    sudo apt-get install -y google-chrome-stable
    sudo apt-get install -y chromium-chromedriver
    which chromedriver
  displayName: 'Install Browsers and WebDrivers'

# Step 3: Set up Apache Maven and build/test the project
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test'