# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# Azure Pipeline for Maven
# Build your Java project, run tests, analyze code, save build artifacts, and more.

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Running Maven tests and cleaning workspace..."
  displayName: 'Echo Step'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml' # Path to the Maven POM file
    mavenOptions: '-Xmx3072m' # JVM options
    javaHomeOption: 'JDKVersion' # Use specified JDK version
    jdkVersionOption: '1.11' # Ensure compatibility with JDK 11
    jdkArchitectureOption: 'x64' # 64-bit Java architecture
    publishJUnitResults: true # Enable publishing JUnit test results
    testResultsFiles: '**/surefire-reports/TEST-*.xml' # Location of test result files
    goals: 'clean test' # Clean build directory and package the project


