name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    # Checkout the repository code
    - uses: actions/checkout@v4

    # Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    # Install Microsoft Edge and Selenium Edge WebDriver
    - name: Install Microsoft Edge and Edge WebDriver
      run: |
        choco install microsoft-edge -y
        choco install selenium-edge-driver -y
        where.exe msedgedriver

         # Install Google Chrome and ChromeDriver
        choco install googlechrome -y
        choco install chromedriver -y
        where.exe chromedriver


    # Build and test with Maven
    - name: Build with Maven
      shell: powershell
      run: mvn clean test

    # Output logs for debugging (optional)
    - name: Print Logs for Debugging
      run: type target/surefire-reports/*.txt